[package]
name = "bqatlas-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
bqatlas-core = { path = "../bqatlas-core" }
bqatlas-contracts = { path = "../bqatlas-contracts" }

[lints]
workspace = true
